/**
 * build.js — Generates timeline.ts and stackTimings.ts from JSON data
 *
 * Usage:
 *   node build.js          → full build
 *   node build.js --check  → validate only (no write)
 *
 * Data files:
 *   data/slides.json  → [{id, time}, ...]   ordered slide entries
 *   data/stacks.json  → [{slide, items, desc}, ...]  stack reveal timings
 */
const fs = require('fs');

const FPS = 30;
const TOTAL_DURATION_SECONDS = 1465;
const CHECK_ONLY = process.argv.includes('--check');

// ─── Load data ───
const slides = JSON.parse(fs.readFileSync('data/slides.json', 'utf-8'));
const stacks = JSON.parse(fs.readFileSync('data/stacks.json', 'utf-8'));

// ─── Validate ───
let errors = 0;

// Check for duplicate IDs
const idCounts = {};
for (const s of slides) {
  idCounts[s.id] = (idCounts[s.id] || 0) + 1;
}
for (const [id, count] of Object.entries(idCounts)) {
  if (count > 1) { console.error(`ERROR: Slide ${id} appears ${count} times`); errors++; }
}

// Check sort order
for (let i = 1; i < slides.length; i++) {
  if (slides[i].time < slides[i - 1].time) {
    console.error(`ERROR: Out of order — S${slides[i].id} (${slides[i].time}s) before S${slides[i - 1].id} (${slides[i - 1].time}s)`);
    errors++;
  }
}

// Check for very short durations
let shortCount = 0;
for (let i = 0; i < slides.length - 1; i++) {
  const dur = slides[i + 1].time - slides[i].time;
  if (dur < 0.3) shortCount++;
}
if (shortCount) console.warn(`WARN: ${shortCount} slides with <0.3s duration`);

// Check gaps
let gapCount = 0;
for (let i = 0; i < slides.length - 1; i++) {
  const dur = slides[i + 1].time - slides[i].time;
  if (dur > 10) {
    console.warn(`WARN: ${dur.toFixed(1)}s gap between S${slides[i].id} (${slides[i].time}s) and S${slides[i + 1].id} (${slides[i + 1].time}s)`);
    gapCount++;
  }
}

// Check stacks reference valid slide IDs
const slideIds = new Set(slides.map(s => s.id));
for (const st of stacks) {
  if (!slideIds.has(st.slide)) {
    console.error(`ERROR: Stack references S${st.slide} which is not in slides.json`);
    errors++;
  }
}

console.log(`\nValidation: ${slides.length} slides, ${stacks.length} stacks, ${errors} errors, ${gapCount} gaps >10s`);

if (errors > 0) {
  console.error('\nFix errors before building.');
  process.exit(1);
}

if (CHECK_ONLY) {
  console.log('Check passed.');
  process.exit(0);
}

// ─── Generate timeline.ts ───
let ts = '// Auto-generated by build.js — DO NOT EDIT BY HAND\n';
ts += `// Generated: ${new Date().toISOString().split('T')[0]}\n\n`;
ts += 'export const SLIDE_TIMELINE: Array<{ slide: number; startTime: number }> = [\n';
for (const s of slides) {
  const mm = Math.floor(s.time / 60);
  const ss = (s.time % 60).toFixed(2).padStart(5, '0');
  ts += `  { slide: ${s.id}, startTime: ${s.time.toFixed(2)} }, // [${mm}:${ss}]\n`;
}
ts += '];\n\n';
ts += `export const FPS = ${FPS};\n`;
ts += `export const TOTAL_DURATION_SECONDS = ${TOTAL_DURATION_SECONDS};\n`;
ts += 'export const TOTAL_FRAMES = TOTAL_DURATION_SECONDS * FPS;\n';

fs.writeFileSync('src/webinar/timeline.ts', ts);
console.log(`Wrote timeline.ts (${slides.length} entries)`);

// ─── Generate stackTimings.ts ───
let st = '// Auto-generated by build.js — DO NOT EDIT BY HAND\n\n';
st += 'export interface StackTiming {\n  slide: number;\n  items: number[];\n}\n\n';
st += 'export const STACK_TIMINGS: StackTiming[] = [\n';
for (const s of stacks) {
  const itemsStr = s.items.map(t => t.toFixed(2)).join(', ');
  st += `  { slide: ${s.slide}, items: [${itemsStr}] },`;
  if (s.desc) st += ` // ${s.desc}`;
  st += '\n';
}
st += '];\n\n';
st += '// Helper: get how many items should be visible for a given slide at a given time\n';
st += 'export function getVisibleStackItems(slide: number, timeInSeconds: number): number {\n';
st += '  const timing = STACK_TIMINGS.find(t => t.slide === slide);\n';
st += '  if (!timing) return 999;\n';
st += '  let count = 0;\n';
st += '  for (const t of timing.items) {\n';
st += '    if (timeInSeconds >= t) count++;\n';
st += '  }\n';
st += '  return count;\n';
st += '}\n';

fs.writeFileSync('src/webinar/stackTimings.ts', st);
console.log(`Wrote stackTimings.ts (${stacks.length} stacks)`);
